name: build

on: [push, workflow_dispatch]

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jurplel/install-qt-action@v4
        with:
          version: '6.8.0'
          modules: 'qtwebsockets'
      - run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
      - run: cmake --build build --config Release
      - run: windeployqt build/Release/warframe_app.exe
      - uses: actions/upload-artifact@v4
        with:
          name: warframe_app-windows
          path: build/Release/

  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jurplel/install-qt-action@v4
        with:
          version: '6.8.0'
          modules: 'qtwebsockets'
      - run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
      - run: cmake --build build
      - uses: actions/upload-artifact@v4
        with:
          name: warframe_app-linux
          path: build/warframe_app